serverengine:
  log: 'STDOUT'
  log_level: 'debug'
  log_rotate_age: 5
  log_rotate_size: 10485760
triglav:
  url: <%= ENV['TRIGLAV_URL'] || 'http://localhost:7800' %>
  credential:
    username: <%= ENV['TRIGLAV_USERNAME'] || 'triglav_test' %>
    password: <%= ENV['TRIGLAV_PASSWORD'] || 'triglav_test' %>
    authenticator: local
vertica:
  watcher_interval: 5
  date_column: d
  timestamp_column: t
  connection_info:
    "vertica://":
      host: <%= ENV['VERTICA_HOST'] %>
      port: <%= ENV['VERTICA_PORT'] %>
      database: <%= ENV['VERTICA_DATABASE'] %>
      user: <%= ENV['VERTICA_USER'] %>
      password: <%= ENV['VERTICA_PASSWORD'] %>
      resource_pool: <%= ENV['VERTICA_RESOURCE_POOL'] %>
      interruptable: true
      read_timeout: 5
